<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RotinaRemote.Core\RotinaRemote.Core.csproj" />
    <ProjectReference Include="..\RotinaRemote.Protocol\RotinaRemote.Protocol.csproj" />
  </ItemGroup>
</Project>
